//
//  User.swift
//  MiAR
//
//  Created by Phan, Ngan on 10/15/17.
//  Copyright © 2017 MiAR. All rights reserved.
//

import UIKit
import Firebase

class User: NSObject {
    // Firebase path: "users/\(uid)"
    //
    // These are generated by FirebaseAuth. See AppDelegate.swift for more details.
    var uid: String
    
    var username: String
    var email: String
    
    init(uid: String, username: String, email: String) {
        self.uid = uid
        self.username = username
        self.email = email
    }
    
    static var currentUser: User?
    
    func save() {
        let ref = Database.database().reference()
        ref.child("users/\(self.uid)/username").setValue(username)
        ref.child("users/\(self.uid)/email").setValue(email)
    }
    
    static func tryGetCurrentUser() {
        if Auth.auth().currentUser != nil {
            User.get(withUid: Auth.auth().currentUser!.uid, onSuccess: { (user) in
                User.currentUser = user
            }, onFailure: { (error) in
                print("Error getting current user")
            })
        }
    }
    
    static func get(withUid uid: String, onSuccess: @escaping (User)->(), onFailure: @escaping (Error)->()) {
        let ref = Database.database().reference()
        ref.child("users").child(uid).observeSingleEvent(of: .value, with: { (snapshot) in
            // Get user value
            let value = snapshot.value as? NSDictionary
            let username = value?["username"] as? String ?? ""
            let email = value?["email"] as? String ?? ""
            let user = User.init(uid: uid, username: username, email: email)
            onSuccess(user)
        }) { (error) in
            print(error.localizedDescription)
            onFailure(error)
        }
    }
}
